from expurtka.putka.config.settings.ceoi import *
from expurtka.putka.config.settings.cerc import *
from expurtka.putka.config.settings.classic import *
from expurtka.putka.config.settings.common import *
from expurtka.putka.config.settings.country_enums import *
from expurtka.putka.config.settings.dynamic import *
from expurtka.putka.config.settings.enums import *
from expurtka.putka.config.settings.local import *
from expurtka.putka.config.settings.rtk import *
from expurtka.putka.config.settings.test import *
from expurtka.putka.config.settings.tomo import *
from expurtka.putka.config.settings.upm import *
