from django.urls import path

from . import views
from .views import ProblemSetCreate, ProblemSetDelete, ProblemSetUpdate

urlpatterns = [
    path(
        "problem_set/<int:problem_set_pk>/",
        views.problem_set_detail,
        name="problem_set_detail",
    ),
    path(
        "problem_set/<int:problem_set_pk>/download/",
        views.problem_set_attempts,
        name="problem_set_attempts",
    ),
    path(
        "problem_set/<int:problem_set_pk>/static/",
        views.problem_set_static,
        name="problem_set_static",
    ),
    path(
        "problem_set/<int:problem_set_pk>/izpit/",
        views.problem_set_izpit,
        name="problem_set_izpit",
    ),
    path(
        "problem_set/<int:problem_set_pk>/tex/",
        views.problem_set_tex,
        name="problem_set_tex",
    ),
    path(
        "problem_set/<int:problem_set_pk>/edit/",
        views.problem_set_edit,
        name="problem_set_edit",
    ),
    path(
        "problem_set/<int:problem_set_pk>/results/",
        views.problem_set_results,
        name="problem_set_results",
    ),
    path(
        "problem_set/<int:problem_set_pk>/move/",
        views.problem_set_move,
        name="problem_set_move",
    ),
    path(
        "problem_set/<int:problem_set_pk>/toggle_visible/",
        views.problem_set_toggle_visible,
        name="problem_set_toggle_visible",
    ),
    path(
        "problem_set/<int:problem_set_pk>/toggle_solution_visibility/",
        views.problem_set_toggle_solution_visibility,
        name="problem_set_toggle_solution_visibility",
    ),
    path(
        "problem_set/create/<int:course_pk>/",
        ProblemSetCreate.as_view(),
        name="problem_set_create",
    ),
    path(
        "problem_set/<int:pk>/update/",
        ProblemSetUpdate.as_view(),
        name="problem_set_update",
    ),
    path(
        "problem_set/<int:pk>/delete/",
        ProblemSetDelete.as_view(),
        name="problem_set_delete",
    ),
    path(
        "<int:problem_set_pk>/progress/",
        views.problem_set_progress,
        name="problem_set_progress",
    ),
    path(
        "<int:problem_set_pk>/progress/groups/<int:group_pk>",
        views.problem_set_progress_groups,
        name="problem_set_progress_groups",
    ),
    path("course/<int:course_pk>/", views.course_detail, name="course_detail"),
    path(
        "course/<int:course_pk>/enroll_in_course/",
        views.enroll_in_course,
        name="enroll_in_course",
    ),
    path(
        "course/<int:course_pk>/unenroll_from_course/",
        views.unenroll_from_course,
        name="unenroll_from_course",
    ),
    path(
        "course/<int:course_pk>/<int:teacher_pk>/demote_to_student",
        views.demote_to_student,
        name="demote_to_student",
    ),
    path(
        "course/<int:course_pk>/<int:student_pk>/promote_to_teacher",
        views.promote_to_teacher,
        name="promote_to_teacher",
    ),
    path(
        "course/<int:course_pk>/<int:student_pk>/toggle_observed",
        views.toggle_observed,
        name="toggle_observed",
    ),
    path(
        "course/<int:course_pk>/progress/<int:user_pk>/",
        views.course_progress,
        name="course_progress",
    ),
    path(
        "course/<int:course_pk>/groups/",
        views.course_groups,
        name="course_groups",
    ),
    path(
        "course/<int:course_pk>/groups/create/",
        views.course_groups_create,
        name="course_groups_create",
    ),
    path(
        "groups/<int:group_pk>/update/",
        views.course_groups_update,
        name="course_groups_update",
    ),
    path(
        "groups/<int:group_pk>/delete",
        views.course_groups_delete,
        name="course_groups_delete",
    ),
    path(
        "groups/<int:group_pk>/confirm_delete",
        views.course_groups_confirm_delete,
        name="course_groups_confirm_delete",
    ),
]
