from django.conf.urls import patterns, url
from . import views
from views import ProblemSetCreate, ProblemSetUpdate, ProblemSetDelete


urlpatterns = patterns(
    '',
    url(r'^problem_set/(?P<problem_set_pk>\d+)/$',
        views.problem_set_detail,
        name='problem_set_detail'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/download/$',
        views.problem_set_attempts,
        name='problem_set_attempts'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/edit/$',
        views.problem_set_edit,
        name='problem_set_edit'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/results/$',
        views.problem_set_results,
        name='problem_set_results'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/move/$',
        views.problem_set_move,
        name='problem_set_move'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/toggle_visible/$',
        views.problem_set_toggle_visible,
        name='problem_set_toggle_visible'),
    url(r'^problem_set/(?P<problem_set_pk>\d+)/toggle_solution_visibility/$',
        views.problem_set_toggle_solution_visibility,
        name='problem_set_toggle_solution_visibility'),
    url(r'^problem_set/create/(?P<course_pk>\d+)/$',
        ProblemSetCreate.as_view(),
        name='problem_set_create'),
    url(r'^problem_set/(?P<pk>\d+)/update/$',
        ProblemSetUpdate.as_view(),
        name='problem_set_update'),
    url(r'^problem_set/(?P<pk>\d+)/delete/$',
        ProblemSetDelete.as_view(),
        name='problem_set_delete'),
    url(r'^(?P<problem_set_pk>\d+)/progress/$',
        views.problem_set_progress,
        name='problem_set_progress'),
    url(r'^course/(?P<course_pk>\d+)/$',
        views.course_detail,
        name='course_detail'),
    url(r'^course/(?P<course_pk>\d+)/enroll_in_course/$',
        views.enroll_in_course,
        name='enroll_in_course'),
    url(r'^course/(?P<course_pk>\d+)/unenroll_from_course/$',
        views.unenroll_from_course,
        name='unenroll_from_course'),
    url(r'^course/(?P<course_pk>\d+)/(?P<teacher_pk>\d+)/demote_to_student$',
        views.demote_to_student,
        name='demote_to_student'),
    url(r'^course/(?P<course_pk>\d+)/(?P<student_pk>\d+)/promote_to_teacher$',
        views.promote_to_teacher,
        name='promote_to_teacher'),
    url(r'^course/(?P<course_pk>\d+)/(?P<student_pk>\d+)/toggle_observed$',
        views.toggle_observed,
        name='toggle_observed'),
    url(r'^course/(?P<course_pk>\d+)/progress/(?P<user_pk>\d+)/$',
        views.course_progress,
        name='course_progress'),
)
