# Generated by Django 5.0.4 on 2024-09-17 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expurtka", "0002_remove_set_sort"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="content",
            table="ui_core_wiki_content",
        ),
        migrations.AlterModelTable(
            name="testcase",
            table="ui_core_results_testcase",
        ),
        migrations.AlterModelTable(
            name="upload",
            table="ui_core_results_upload",
        ),
        migrations.AlterModelTable(
            name="usertest",
            table="ui_core_results_usertest",
        ),
    ]
