# Generated by Django 5.0.4 on 2024-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expurtka", "0003_alter_content_table_alter_testcase_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="secret",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="solution",
            field=models.TextField(default=""),
        ),
    ]
