# Generated by Django 4.1.2 on 2022-11-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_initial"),
        ("attempts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="problems.part",
            ),
        ),
    ]
