# Generated by Django 4.1.2 on 2023-02-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_probleminstance"),
        ("attempts", "0003_alter_attempt_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="problem_instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="courses.probleminstance",
            ),
        ),
        migrations.AddField(
            model_name="historicalattempt",
            name="problem_instance",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="courses.probleminstance",
            ),
        ),
    ]
