# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 09:27
from __future__ import unicode_literals

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0006_auto_20160118_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="feedback",
            field=models.TextField(
                default="[]", validators=[utils.is_json_string_list]
            ),
        ),
        migrations.AlterField(
            model_name="historicalattempt",
            name="feedback",
            field=models.TextField(
                default="[]", validators=[utils.is_json_string_list]
            ),
        ),
    ]
