# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def add_submission_date(apps, schema_editor):
        Attempt = apps.get_model('attempts', 'Attempt')
        HistoricalAttempt = apps.get_model('attempts', 'HistoricalAttempt')
        submission_dates = {}
        for historical_attempt in HistoricalAttempt.objects.all():
            part_id, user_id = historical_attempt.part_id, historical_attempt.user_id
            date = historical_attempt.history_date
            historical_attempt.submission_date = date
            historical_attempt.save()
            if (part_id, user_id) not in submission_dates or date > submission_dates[(part_id, user_id)]:
                submission_dates[(part_id, user_id)] = date
        for attempt in Attempt.objects.all():
            attempt.submission_date = submission_dates[(attempt.part_id, attempt.user_id)]
            attempt.save()

    dependencies = [
        ('attempts', '0007_auto_20161004_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalattempt',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            code=add_submission_date,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submission_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalattempt',
            name='submission_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
