# Generated by Django 2.0.13 on 2022-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0008_add_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalattempt",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
