# Generated by Django 4.1.2 on 2022-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0009_historicalattempt_history_change_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalattempt",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical attempt",
                "verbose_name_plural": "historical attempts",
            },
        ),
        migrations.AlterField(
            model_name="historicalattempt",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
