# Generated by Django 4.1.7 on 2023-02-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursegroup",
            options={"ordering": ["title", "description"]},
        ),
    ]
