# Generated by Django 4.1.2 on 2023-02-19 11:00

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_alter_historicalproblem_visible_and_more"),
        ("courses", "0003_alter_coursegroup_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=False, verbose_name="Visible")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="problems.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.problemset",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "problem_set",
            },
            bases=(utils.models.OrderWithRespectToMixin, models.Model),
        ),
    ]
