# Generated by Django 2.0.13 on 2022-10-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institution",
                to="courses.Institution",
            ),
        ),
    ]
