# Generated by Django 4.1.2 on 2022-11-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='courses.problemset'),
        ),
    ]
