# Generated by Django 4.1.2 on 2023-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_part_problem_alter_problem_problem_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproblem",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Visible"),
        ),
        migrations.AddField(
            model_name="problem",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Visible"),
        ),
    ]
