# Generated by Django 4.1.2 on 2023-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_historicalproblem_visible_problem_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproblem",
            name="visible",
            field=models.BooleanField(default=False, verbose_name="Visible"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="visible",
            field=models.BooleanField(default=False, verbose_name="Visible"),
        ),
    ]
