# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20160809_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalProblem',
            new_name='HistoricalProblemContents',
        ),
        migrations.RenameModel(
            old_name='Problem',
            new_name='ProblemContents',
        ),
        migrations.AlterModelOptions(
            name='historicalproblemcontents',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical problem contents'},
        ),
    ]
