# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20160809_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpart',
            name='problem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='problems.ProblemContents'),
        ),
    ]
