# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20161004_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproblem',
            name='verify_attempt_tokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='verify_attempt_tokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalproblem',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('octave', 'Octave'), ('r', 'R')], default='python', max_length=8),
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('octave', 'Octave'), ('r', 'R')], default='python', max_length=8),
        ),
    ]
