# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-07 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_add_verify_attempt_tokens'),
        ('problems', '0014_auto_20170509_0919'),
    ]

    operations = [
    ]
