# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproblem',
            name='verify_attempt_tokens',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='verify_attempt_tokens',
            field=models.BooleanField(default=True),
        ),
    ]
