# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.ProblemContents'),
        ),
    ]
