# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20160809_1231'),
        ('problems', '0016_problem_problem_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='course_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualproblems', to='courses.Course'),
        ),
    ]
