# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_problem_course_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='course_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualproblems', to='courses.ProblemSet'),
        ),
    ]
