# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_auto_20160810_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_set',
            field=models.BooleanField(default=True),
        ),
    ]
