# Generated by Django 2.0.13 on 2022-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0018_auto_20190411_0446"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpart",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproblem",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
