# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_remove_problem_problem_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='course_set',
            new_name='problem_set',
        ),
    ]
