# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


def create_problems(apps, schema_editor):
    ProblemContents = apps.get_model('problems', 'ProblemContents')
    Problem = apps.get_model('problems', 'Problem')
    for pc in ProblemContents.objects.all():
        p = Problem(problem_set=pc.problem_set,
                    problem_contents=pc,
                    editable=True)
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_auto_20160810_1132'),
    ]

    operations = [
        migrations.RunPython(create_problems),
    ]
